spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/travel
    username: travel
    password: travel
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info