spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
  mvc:
    problemdetails:
      enabled: true
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health,info